mylock/urls.py
from django.urls import path
from django.conf.urls import url
from mylock import views

app_name = 'mylock'
urlpatterns = [
    path('', views.home, name='home'),
    url(r'^validate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.validate_request, name='validate'),
    url(r'^verificate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.verificate_account, name='verificate'),
    path('users/', views.users, name='users'),
    path('users/add_user/', views.add_user, name='add_user'),
    path('users/add_user/<str:new_user>/setup_fingerprint/', views.setup_fingerprint, name='setup_fingerprint'),
    path('users/add_user/<str:new_user>/setup_facial_recognition/', views.setup_facial_recognition_explanation, name='setup_facial_recognition_explanation'),
    path('users/add_user/<str:new_user>/setup_facial_recognition/<int:photo_number>/', views.setup_facial_recognition, name='setup_facial_recognition'),
    path('users/<str:user>/', views.user_detail, name='user_detail'),
    path('users/<str:user>/delete_user/', views.delete_user, name='delete_user'),
    path('log/', views.log, name='log'),
    path('backup_password/', views.backup_password, name ='backup_password'),
]

smartLock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', TemplateView.as_view(template_name='smartlock.html'), name='smartlock'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('mylock/', include('mylock.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mylock/models.py
from django.utils.timezone import localtime
from django.db import models

# Create your models here.
class CustomUser(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    username = models.CharField(max_length=50)
    fingerprint_ID = models.CharField(max_length=3)
    is_active = models.BooleanField(default=True)

    class Meta:
        permissions = (
            ("can_see_backup_password", "Can see backup password"),
        )

    def __str__(self):
        return self.username

    def details(self):
       return self.name, self.email, self.username

class Log(models.Model):
    username = models.CharField(max_length=200)
    timestamp = models.DateTimeField("date lock used")

    def __str__(self):
        time = localtime(self.timestamp)
        return str(time.strftime("%d-%m-%Y")) + ", " + str(time.strftime("%H:%M")) + ", " + self.username

class Active_Sessions(models.Model):
    user = models.CharField(max_length=200)
    session_key = models.CharField(max_length=200)

mylock/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.contrib.auth.models import User, Group
from django.contrib.auth import password_validation
from .models import CustomUser

class UserForm(ModelForm):
    password = forms.CharField(
        label="password",
        strip=False,
        widget=forms.PasswordInput,
    )

    password_confirmation = forms.CharField(
        label="password_confirmation",
        strip=False,
        widget=forms.PasswordInput,
    )

    class Meta:
        model = CustomUser

        fields = ["name", "email", "username"]

    def is_valid(self):
        valid = super(UserForm, self).is_valid()

        if not valid:
            self.add_error(valid)

        try:
            CusomUser.objects.get(username=self.cleaned_data["username"])
            self.add_error("username", "Username already exists")

        except:
            pass

        if self.cleaned_data.get("password") != self.cleaned_data.get("password_confirmation"):
            self.add_error("password_confirmation", "The two password fields didn't match")

        if len(self.errors) == 0:
            return True

        else:
            return False

    def login_save(self, commit=True):
        login = User.objects.create_user(username=self.cleaned_data.get("username"))
        login.set_password(self.cleaned_data.get("password"))
        login.is_active = False
        login.save()
        backup_password_toggler = Group.objects.get(name="backup_password_toggler")
        login.groups.add(backup_password_toggler)

mylock/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User, Group, Permission
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_validation_token, account_verification_token
from django.core.mail import send_mail
from .models import CustomUser, Log
from .forms import UserForm
from background_task import background
import mylock.main
from mylock.pin_code import get_code
import subprocess

import sys
sys.path.append("/home/pi/smartLock")
from facial_recognition import train_new_user

import serial
for i in range(10):
    try:
        ser = serial.Serial('/dev/ttyACM' + str(i), 9600)
        break
    except:
        pass

# Create your views here.

@login_required
def home(request):
    context = {}
    if not request.user.is_superuser:
      context["fingerprint_ID"] = CustomUser.objects.filter(username=request.user.username).values_list("fingerprint_ID", flat=True)[0]
    return render(request, 'mylock/home.html', context)

@login_required
def users(request):
    context = {}
    context["users_list"] = [str(i) for i in CustomUser.objects.all()]
    return render(request, 'mylock/users.html', context)

@login_required
@user_passes_test(lambda i: i.is_superuser, login_url='mylock:home')
def add_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            login_user = form.login_save()
            current_site = get_current_site(request)
            subject = 'Validate your account'
            message = render_to_string('mylock/validation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token':account_validation_token.make_token(user),
            })
            from_email = "CW2B3.smartLock@gmail.com"
            to_email = "CW2B3.smartLock@gmail.com"
            send_mail(subject, message, from_email, [to_email])

            return render(request, 'mylock/add_user.html', {'text': 'Please confirm your email address to complete the registration'})
    else:
        form = UserForm()

    return render(request, 'mylock/add_user.html', {'form': form})

def validate_request(request, uidb64, token):
    context = {}
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_validation_token.check_token(user, token):
            current_site = get_current_site(request)
            subject = 'Verificate your account'
            message = render_to_string('mylock/verification_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token':account_verification_token.make_token(user),
            })
            from_email = "CW2B3.smartLock@gmail.com"
            to_email = CustomUser.objects.filter(username=user).values_list("email", flat=True)[0]
            send_mail(subject, message, from_email, [to_email])
    return render(request, 'mylock/validate_account.html', context)

def verificate_account(request, uidb64, token):
    context = {}
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_verification_token.check_token(user, token):
        login_user = User.objects.get(username=user)
        user.is_active = True
        user.save()
        login_user.is_active = True

        login_user.save()
        context["text"] = "Thank you for your email confirmation. Now you can login your account."
    else:
        context["text"] = "Activation link is invalid!"
    return render(request, 'mylock/verificate_account.html', context)

@user_passes_test(lambda i: not i.is_superuser and CustomUser.objects.filter(username=i.username).values_list("fingerprint_ID", flat=True)[0] == "", login_url='mylock:home')
def setup_fingerprint(request, new_user):
    context = {}
    context["title"] = "Setup your account"
    if (request.GET.get('fingerprint_button')):
        subprocess.call("/home/pi/smartLock/kill_authenticate")
        mylock.main.add_new_fingerprint(new_user)
        return HttpResponseRedirect(reverse('mylock:setup_facial_recognition_explanation', kwargs={'new_user': new_user}))
    return render(request, 'mylock/setup_fingerprint.html', context)

@login_required
@user_passes_test(lambda i: not i.is_superuser, login_url='mylock:home')
def setup_facial_recognition_explanation(request, new_user):
    context = {}
    context["title"] = "Setup your account"
    if(request.GET.get('photo_button')):
        mylock.main.start_picture_procedure()
        return HttpResponseRedirect(reverse('mylock:setup_facial_recognition', kwargs={'new_user': new_user, 'photo_number': 0}))
    return render(request, 'mylock/setup_facial_recognition_explanation.html', context)

@login_required
@user_passes_test(lambda i: not i.is_superuser, login_url='mylock:home')
def setup_facial_recognition(request, new_user, photo_number):
    context = {}
    context["title"] = "Setup your account"
    context["text"] = str(photo_number) + "/5 photos taken"
    context["photo_number"] = photo_number
    context["next_photo_number"] = photo_number + 1
    if photo_number < 0 or photo_number > 5:
        return HttpResponseRedirect(reverse('mylock:home'))
    elif 0 < photo_number < 5:
        mylock.main.add_new_face(new_user, photo_number)
    elif photo_number == 5:
        mylock.main.add_new_face(new_user, photo_number)
        context["succes_message"] = "Setup completed!"
        finish_new_user()
    return render(request, 'mylock/setup_facial_recognition.html', context)

@background(schedule=1)
def finish_new_user():
    subprocess.Popen(["python3", "/home/pi/smartLock/authenticate.py"])
    train_new_user()

@login_required
def user_detail(request, user):
    context = {}
    context["title"] = "Details from user: " + str(user)
    context["user"] = str(user)
    detail = CustomUser.objects.get(username=user)
    context["user_detail"] = detail.details()
    return render(request, 'mylock/user_detail.html', context)

@login_required
@user_passes_test(lambda i: i.is_superuser, login_url='mylock:home')
def delete_user(request, user):
    context = {}
    delete_info = CustomUser.objects.get(username=user)
    delete_info.delete()
    delete_login = User.objects.get(username=user)
    delete_login.delete()
    mylock.main.delete_user_photos(user)
    return render(request, 'mylock/delete_user.html', context)

@login_required
def log(request):
    context = {}
    context["title"] = "List with the log of the lock"
    context["log_list"] = [str(i).split(",") for i in Log.objects.all()][::-1]
    return render(request, 'mylock/log.html', context)

@login_required
@user_passes_test(lambda i: not i.is_superuser, login_url='mylock:home')
@permission_required('mylock.can_see_backup_password', login_url='mylock:home')
def backup_password(request):
    context = {}
    context["title"] = "Backup password"
    if(request.GET.get('backup_password_button')):
        pincode = get_code()
        ser.write(str(pincode).encode())
        subject = "Backup password"
        message = "Your backup password is: " + str(pincode)
        from_email = "CW2B3.smartLock@gmail.com"
        to_email = CustomUser.objects.filter(username=request.user.username).values_list("email", flat=True)[0]
        send_mail(subject, message, from_email, [to_email])
        backup_password_toggler = Group.objects.get(name="backup_password_toggler")
        permission = Permission.objects.get(name="Can see backup password")
        backup_password_toggler.permissions.remove(permission)
        log = Log(username = request.user.username, timestamp= timezone.now())
        log.save()
        return HttpResponseRedirect(reverse('mylock:home'))
    return render(request, 'mylock/backup_password.html', context)

mylock/templates/mylock/add_user.html
{% extends 'mylock_base.html' %}

{% load widget_tweaks %}

{% block urltitle %}smartLock | Add user{% endblock %}

{% block content %}
<head>
    <style>
    @media(min-width: 768px) {
      .field-label-responsive {
        padding-top: .5rem;
        text-align: right;
      }
    }
    </style>
    
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

</head>
{% if text is None %}
<body>
<div class="container">
    <form class="form-horizontal" role="form" method="post" action="/mylock/users/add_user/">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <h1>Add new user</h1>
                <p>Enter the details of the user that will be added to the lock.</p>
                <p>You need to enter the full name, a valid e-mailaddress, an arbitrary (unused) username and a secure password</p>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem">
                            <i class="fa fa-user"></i>
                        </div>
                          {% if form.is_bound %}
                            {% if form.name.errors %}
                              {% render_field form.name|attr:"placeholder:Enter your Name" class="form-control is-invalid" %}
                              {% for error in form.name.errors %}
                                <div class="invalid-feedback">
                                  {{error}}
                                </div>    
                              {% endfor %}
                            {% else %}
                              {% render_field form.name|attr:"placeholder:Enter your Name" class="form-control is-valid" %}
                            {% endif %}
                          {% else %}  
                            {% render_field form.name|attr:"placeholder:Enter your Name" class="form-control" %}
                          {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-envelope"></i></div>
                          {% if form.is_bound %}
                            {% if form.email.errors %}
                              {% render_field form.email|attr:"placeholder:Enter your Email" class="form-control is-invalid" %}
                              {% for error in form.email.errors %}
                                <div class="invalid-feedback">
                                  {{error}}
                                </div>
                              {% endfor %}
                            {% else %}
                              {% render_field form.email|attr:"placeholder:Enter your Email" class="form-control is-valid" %}
                            {% endif %}
                          {% else %}
                            {% render_field form.email|attr:"placeholder:Enter your Email" class="form-control" %}
                          {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-users"></i></div>
                          {% if form.is_bound %}
                            {% if form.username.errors %}
                              {% render_field form.username|attr:"placeholder:Enter your Username" class="form-control is-invalid" %}
                              {% for error in form.username.errors %}
                                <div class="invalid-feedback">
                                  {{error}}
                                </div>
                              {% endfor %}
                            {% else %}
                              {% render_field form.username|attr:"placeholder:Enter your Username" class="form-control is-valid" %}
                            {% endif %}
                          {% else %}
                            {% render_field form.username|attr:"placeholder:Enter your Username" class="form-control" %}
                          {% endif %}

                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-lock"></i></div>
                          {% if form.is_bound %}
                            {% if form.password.errors %}
                              {% render_field form.password|attr:"placeholder:Enter your Password" class="form-control is-invalid" %}
                              {% for error in form.password.errors %}
                                <div class="invalid-feedback">
                                  {{error}}
                                </div>
                              {% endfor %}
                            {% else %}
                              {% render_field form.password|attr:"placeholder:Enter your Password" class="form-control is-valid" %}
                            {% endif %}
                          {% else %}
                            {% render_field form.password|attr:"placeholder:Enter your Password" class="form-control" %}
                          {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
            </div>
            <div class="col-md-6">
                <div class="form-group has-danger">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-lock"></i></div>
                          {% if form.is_bound %}
                            {% if form.password_confirmation.errors %}
                              {% render_field form.password_confirmation|attr:"placeholder:Confirm your Password" class="form-control is-invalid" %}
                              {% for error in form.password_confirmation.errors %}
                                <div class="invalid-feedback">
                                  {{error}}
                                </div>
                              {% endfor %}
                            {% else %}
                              {% render_field form.password_confirmation|attr:"placeholder:Confirm your Password" class="form-control is-valid" %}
                            {% endif %}
                          {% else %}
                            {% render_field form.password_confirmation|attr:"placeholder:Confirm your Password" class="form-control" %}
                          {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <button type="submit" class="btn btn-outline-success"><i class="fa fa-user-plus"></i> Add user</button>
            </div>
        </div>
    </form>
</div>
</body>
{% else %}
  <head>
    <meta http-equiv="refresh" content="5; url={% url 'mylock:home' %}" />
  </head>

{{text}}
{% endif %}
{% endblock %}

mylock/templates/mylock/backup_password.html
{% extends 'mylock_base.html' %}

{% block urltitle %}backup password{% endblock %}

{% block title %}{{title}}{% endblock %}

{% block content %}
  <form method="get">
    <button type="submit" class="btn btn-outline-primary" value="Backup password" name="backup_password_button"><i class="fas fa-envelope"></i> Mail backup password</button>
  </form>
{% endblock %}

mylock/templates/mylock/delete_user.html
<meta http-equiv="refresh" content="0; url={% url 'mylock:users'%}" />

mylock/templates/mylock/home.html
{% extends 'mylock_base.html' %}

{% block urltitle %}smartLock | Home{% endblock %}

{% block title %}Welcome to smartLock{% endblock %}

{% block content %}
{% if not request.user.is_superuser and fingerprint_ID == '' %}
  <head>
    <meta http-equiv="refresh" content="0; url={% url 'mylock:setup_fingerprint' new_user=request.user.username %}" />
  </head>
{% endif %} 
  <p>Hi {{user.username}}!</p>
  <p>In this environment you can consult the log with a list of all people who recently gained access through this lock, you can also access a list of all people who are allowed entry by this lock in the first place.</p>
  <p>If you have administrative privileges you can manage this list by deleting people from it or adding them to it.</p>
{% if request.user.is_superuser %}
  <p>You have administrative privileges</p>
{% endif %}
  <h4>To get started you can access the modules in the navigational pane</h4>
{% endblock %}

mylock/templates/mylock/log.html
{% extends 'mylock_base.html' %}

{% block urltitle %}log{% endblock %}

{% block title %}{{title}}{% endblock %}

{% block content %}
  <table class="table table-bordered">
    <thead class="thead-light">
      <tr>
        <th scope="col">Day</th>
        <th scope="col">Time</th>
        <th scope="col">Username</th>
      </tr>
    </thead>
    <tbody>
      {% for log in log_list %}
        <tr>
          {% for info in log %}
            <td>{{info}}</td>
          {% endfor %}
        </tr>
      {% endfor %}
    </tbody>
  </table> 
{% endblock %}

mylock/templates/mylock/setup_facial_recognition.html
{% extends 'mylock_base.html' %}

{% block urltitle %}setup facial recognition{% endblock %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
  .loader {
    border: 16px solid #f3f3f3;
    border-radius: 50%;
    border-top: 16px solid #3498db;
    width: 120px;
    height: 120px;
    -webkit-animation: spin 2s linear infinite; /* Safari */
    animation: spin 2s linear infinite;
  }
  /* Safari */
  @-webkit-keyframes spin {
    0% { -webkit-transform: rotate(0deg); }
    100% { -webkit-transform: rotate(360deg); }
  }
  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
  </style>
  <script>
  $(document).ready(function(){
    $("button").click(function(){
      $("button").hide();
      $("#loader").show();
    });
  });
  </script>
</head>
<p>{{text}}</p>
<p>{{test}}</p>
{% if photo_number >= 0 and photo_number < 5%}
  <head>
    <meta http-equiv="refresh" content="0; url={% url 'mylock:setup_facial_recognition' new_user=request.user.username photo_number=next_photo_number %}" />
  </head>
  <div id="loader" class="loader"></div>
{% elif photo_number == 5 %}
  <head>
    <meta http-equiv="refresh" content="5; url={% url 'mylock:users' %}" />
  </head>
<p>{{succes_message}}</p>
{% endif %}
{% endblock %}

mylock/templates/mylock/setup_facial_recognition_explanation.html
{% extends 'mylock_base.html' %}
{% load static %}

{% block urltitle %}setup facial recognition{% endblock %}

{% block title %}Add pictures of your face to the database{% endblock %}

{% block content %}
{{text}}
  <form method="get">
    <button type="submit" class="btn btn-outline-primary" value="Take photo" name="photo_button">Take photo <i class="fas fa-camera"></i></button>
  </form>
  <p>In this step you will take five pictures of your face for us to put in the database. With these pictures the smart lock will be able to recognize you when you want to unlock your door. To ensure the smart lock recognizes you every time, you will need to tilt your face in a different direction for every picture. Please follow the steps below:</p>
  
  <h4>Picture 1:</h4>
  <p>- Copy the stance of the face below and look at the camera with a straight face</p>
  <p>- Place your hand around the door handle and remove it</p>
  <p>- Wait for the door handle to flash a red light, this means the picture was succesfully taken</p>
  <img src="{% static 'Face1.png' %}" class="img-fluid">
  
  <h4>Picture 2:</h4>
  <p>- Copy the stance of the face below and look at the camera with a straight face</p>
  <p>- Place your hand around the door handle and remove it</p>
  <p>- Wait for the door handle to flash a red light, this means the picture was succesfully taken</p>
  <img src="{% static 'Face2.png' %}" class="img-fluid">

  <h4>Picture 3:</h4>
  <p>- Copy the stance of the face below and look at the camera with a straight face</p>
  <p>- Place your hand around the door handle and remove it</p>
  <p>- Wait for the door handle to flash a red light, this means the picture was succesfully taken</p>
  <img src="{% static 'Face3.png' %}" class="img-fluid">

  <h4>Picture 4:</h4>
  <p>- Copy the stance of the face below and look at the camera with a straight face</p>
  <p>- Place your hand around the door handle and remove it</p>
  <p>- Wait for the door handle to flash a red light, this means the picture was succesfully taken</p>
  <img src="{% static 'Face4.png' %}" class="img-fluid">

  <h4>Picture 5:</h4>
  <p>- Copy the stance of the face below and look at the camera with a straight face</p>
  <p>- Place your hand around the door handle and remove it</p>
  <p>- Wait for the door handle to flash a red light, this means the picture was succesfully taken</p>
  <img src="{% static 'Face5.png' %}" class="img-fluid"/>

{% endblock %}

mylock/templates/mylock/setup_fingerprint.html
{% extends 'mylock_base.html' %}

{% block urltitle %}setup fingerprint{% endblock %}

{% block title %}Add your fingerprint to the database{% endblock %}

{% block content %}
<p>In this step you will scan your finger two times so we can store it in our database. Just click on the “Take fingerprint” button above and follow the steps below:</p>
<p>STEP 1: Once the fingerprint scanner turns red, place your finger on the scanner* untill the red light turns off.</p>
<p>STEP 2: Wait for the fingerprint scanner to turn red again and place the same finger on the scanner untill the red light turns off. (If the fingerprint scanner turns red again, just repeat ‘STEP 2’ untill succes).</p4>
<p>*The fingerprint scanner is located on the left side of the door handle</p>
<br>
<form method="get">
  <button type="submit" class="btn btn-outline-primary" value="Take fingerprint" name="fingerprint_button">Take fingerprint <i class="fas fa-fingerprint"></i></button>
</form>

{% endblock %}

mylock/templates/mylock/user_detail.html
{% extends 'mylock_base.html' %}

{% block urltitle %}smartLock | {{user}}{% endblock %}

{% block title %}Details of {{user}}{% endblock %}

{% block content %}
  <table class="table table-bordered table-responsive-sm">
    <thead class="thead-light">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Username</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        {% for info in user_detail %}
        <td>{{info}}</td>
        {% endfor %}
      </tr>
    </tbody>
  </table>
  {% if request.user.is_superuser %}
  <a href="/mylock/users/{{user}}/delete_user" class="btn btn-outline-danger" role="button"><i class="fa fa-times"></i>  Delete user</a>
  {% endif %}
{% endblock %}

mylock/templates/mylock/users.html
{% extends 'mylock_base.html' %}

{% block urltitle %}smartLock | Users{% endblock %}

{% block title %}List of all the users{% endblock %}

{% block content %}
  <p>This page contains a list of all the users who may gain entry by this lock, you can select a username to see more detailed information of the respective user.</p>
  <div class="list-group">
  {% for user in users_list %}
    <a href="/mylock/users/{{user}}" class="list-group-item list-group-item-action">{{user}}</a>
  {% endfor %}
  </div>
  {% if request.user.is_superuser %}
  <a href="{% url 'mylock:add_user' %}" class="btn btn-outline-success" style="margin-top: 15px;" role="button"><i class="fa fa-user-plus"></i> Add user</a>
  {% endif %}
{% endblock %}

mylock/templates/mylock/validate_account.html
{% extends 'base.html' %}

{% block urltitle %}validate account{% endblock %}

{% block title %}{{title}}{% endblock %}

{% block content %}
  <head>
    <meta http-equiv="refresh" content="5; url={% url 'smartlock' %}" />
  </head>
  <p>{{text}}</p>
{% endblock %}

mylock/templates/mylock/validation_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'mylock:validate' uidb64=uid token=token %}
{% endautoescape %}

mylock/templates/mylock/verification_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'mylock:verificate' uidb64=uid token=token %}
{% endautoescape %}