mylock/urls.py
from django.urls import path
from django.conf.urls import url
from mylock import views

app_name = 'mylock'
urlpatterns = [
    path('', views.home, name='home'),
    url(r'^validate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.validate_request, name='validate'),
    url(r'^verificate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.verificate_account, name='verificate'),
    path('users/', views.users, name='users'),
    path('users/add_user/', views.add_user, name='add_user'),
    path('users/add_user/<str:new_user>/setup_fingerprint/', views.setup_fingerprint, name='setup_fingerprint'),
    path('users/add_user/<str:new_user>/setup_facial_recognition/', views.setup_facial_recognition_explanation, name='setup_facial_recognition_explanation'),
    path('users/add_user/<str:new_user>/setup_facial_recognition/<int:photo_number>/', views.setup_facial_recognition, name='setup_facial_recognition'),
    path('users/<str:user>/', views.user_detail, name='user_detail'),
    path('users/<str:user>/delete_user/', views.delete_user, name='delete_user'),
    path('log/', views.log, name='log'),
    path('backup_password/', views.backup_password, name ='backup_password'),
]

smartLock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', TemplateView.as_view(template_name='smartlock.html'), name='smartlock'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('mylock/', include('mylock.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>{% block urltitle %}<none>{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'Thumbnail.png' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <style>
    section {margin-left: 15px;
             margin-right: 15px;}
    h1.styling {font-size: 30px;
                margin-top: 15px;}
    .blue_color {color: #008ae6 !important;}
  </style>
  <body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'smartlock' %}">
        <img src="{% static 'Logo.png' %}" width="200" height="30" alt="Logo">
      </a>
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link blue_color" href="{% url 'login'%}">Login</a>
        </li>
      </ul>
    </nav>
    <div>
      <section>
        <h1 class="styling">{% block title %}<none>{% endblock %}</h1>
        <p>{% block content %}<none>{% endblock %}</p>
      </section>
    </div>
  </body>
</html>

templates/mylock_base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>{% block urltitle %}<none>{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'Thumbnail.png' %}"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <style>
    section {margin-left: 15px;
             margin-right: 15px;}
    h1.styling {font-size: 30px;
                margin-top: 15px;}
    .blue_color {color: #008ae6 !important;}
  </style>
  <body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'mylock:home' %}">
        <img src="{% static 'Logo.png' %}" width="200" height="30" alt="Logo">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mylock:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mylock:users' %}">Users</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mylock:log' %}">Log</a>
          </li>
          {% if perms.mylock.can_see_backup_password and not.request.user.is_superuser%}  
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mylock:backup_password' %}">Backup password</a>
            </li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link blue_color" href="{% url 'logout'%}">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
    <div>
      <section>
        <h1 class="styling">{% block title %}<none>{% endblock %}</h1>
        <p>{% block content %}{% endblock %}</p>
      </section>
    </div>
    <script type="text/javascript">
      $(document).ready(function() {
	var pathname = window.location.pathname;
	$('.nav > li > a[href="'+pathname+'"]').parent().addClass('active');
      })
    </script>
  </body>
</html>

templates/smartlock.html
{% extends 'base.html' %}

{% block urltitle %}smartLock | not logged in{% endblock %}
{% block title %}Welcome to smartlock!{% endblock %}

{% block content %}
  <p>In this environment you can consult the log with a list of all people who recently gained access through this lock, you can also access a list of all people who are allowed entry through this lock in the first place.</p>
  <p>If you have administrative privileges you can manage this list by deleting people from it or adding them to it.</p>
  <h4>To get started you should log in and the options should appear in the navigation pane</h4>
{% endblock %}